# utilities and git
  - name: install on redhat
    block:
    - name: install utilites
      yum:
        name:
        - wget
        - unzip
        - curl
        - net-tools
        - tree

    - name: install git
      yum:
        name: git
        state: latest
        update_cache: yes
    when: ansible_os_family | lower == 'redhat'

  - name: install on debian
    block:
    - name: install utilites
      apt:
        name:
        - wget
        - unzip
        - curl
        - net-tools
        - tree

    - name: install on ubuntu
      apt:
        name: git
        state: latest
        update_cache: yes
    when: ansible_os_family | lower == 'debian'
