---
- name: ci machines provisionned
  hosts: jenkins2 
  become: yes
  roles:
    - maven-role
    - jenkins-role
#    - lrk.sonarqube
    - sonarqube-role

  tasks:
    - name: jenkins started
      systemd:
        name: jenkins
        state: started
        enabled: true 
