---
- name: ci machines provisionned
  hosts: ci 
  become: yes
  roles:
    - maven-role
    - jenkins-role
    - sonarqube-role
    - artifactory-role

  tasks:
    - name: jenkins started
      systemd:
        name: jenkins
        state: started
        enabled: true 
